/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto2;

import java.io.FileNotFoundException;
import javax.swing.JOptionPane;

/**
 *
 * @author andresespinoza
 */
public class MainModal extends javax.swing.JFrame {
    Arbol arbol;
    String actividad;
    NodoArbol navegador;
    /**
     * Creates new form MainModal
     */
    public MainModal() {
        initComponents();
    }
    
    public MainModal(Arbol nuevoArbol) throws FileNotFoundException{
        this.arbol = nuevoArbol;
        initComponents();
        arbol.leerDatos();
        String arbolImpreso = arbol.imprimir();
        botonSi.setVisible(false);
        botonNo.setVisible(false);
        this.actividad = "";
        this.navegador = arbol.getRaiz();
        botonGuardarEnArchivo.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historialDePreguntas = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        botonVerArbol = new javax.swing.JButton();
        botonNuevaSesion = new javax.swing.JButton();
        labelPregunta = new javax.swing.JLabel();
        botonNo = new javax.swing.JButton();
        botonSi = new javax.swing.JButton();
        botonGuardarEnArchivo = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenido Al Adivinador de Animales");

        historialDePreguntas.setColumns(20);
        historialDePreguntas.setRows(5);
        jScrollPane1.setViewportView(historialDePreguntas);

        jLabel2.setText("Historial de preguntas y repuestas:");

        botonVerArbol.setText("Ver Arbol");
        botonVerArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerArbolActionPerformed(evt);
            }
        });

        botonNuevaSesion.setText("Nueva Sesion");
        botonNuevaSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaSesionActionPerformed(evt);
            }
        });

        labelPregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPregunta.setText("Inicia una nueva sesion para comenzar!");

        botonNo.setText("No");
        botonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNoActionPerformed(evt);
            }
        });

        botonSi.setText("Si");
        botonSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiActionPerformed(evt);
            }
        });

        botonGuardarEnArchivo.setText("Guardar en Archivo");
        botonGuardarEnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarEnArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonNuevaSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(botonGuardarEnArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(labelPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(botonSi)
                                .addGap(18, 18, 18)
                                .addComponent(botonNo))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(botonVerArbol, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevaSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGuardarEnArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(labelPregunta)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSi, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(botonVerArbol, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerArbolActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, arbol.imprimir());
    }//GEN-LAST:event_botonVerArbolActionPerformed

    private void botonNuevaSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaSesionActionPerformed
        botonSi.setVisible(true);
        botonNo.setVisible(true);
        actividad = "";
        navegador = arbol.getRaiz();
        labelPregunta.setText("El animal "+navegador.getValor()+ "?");
        this.actividad += labelPregunta.getText()+"\n";
        historialDePreguntas.setText(actividad);
        
    }//GEN-LAST:event_botonNuevaSesionActionPerformed

    private void botonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNoActionPerformed
        // TODO add your handling code here:
        this.actividad += "No!\n";
        historialDePreguntas.setText(actividad);
        if(navegador.esHoja()){
            String animal = JOptionPane.showInputDialog("Cual era tu animal?");
            String nuevaPregunta = JOptionPane.showInputDialog("Que diferencia a un "+navegador.getValor() + " de un "+animal+"?");
            NodoArbol nuevaHoja = new NodoArbol(animal);
            
            //Creo una nueva pregunta
            NodoArbol pregunta = new NodoArbol(nuevaPregunta);
            
            //Veo cual es la opcion positiva y negativa
            int respuesta = JOptionPane.showConfirmDialog(null,"El animal "+navegador.getValor()+" "+pregunta.getValor()+"?", "Seleccione si o no",JOptionPane.YES_NO_OPTION);
            
            //Configuramos los nuevos nodos hoja segun la confirmacion del usuario
            if(respuesta == JOptionPane.YES_OPTION){
                pregunta.setHijoAfirmativo(navegador);
                pregunta.setHijoNegativo(nuevaHoja);
                pregunta.setPadre(navegador.getPadre());
                nuevaHoja.setPadre(pregunta);
            }
            else if(respuesta == JOptionPane.NO_OPTION){
                pregunta.setHijoNegativo(navegador);
                pregunta.setHijoAfirmativo(nuevaHoja);
                pregunta.setPadre(navegador.getPadre());
                nuevaHoja.setPadre(pregunta);
            }
            
            //La integro en el arbol
            if(navegador.getPadre().getHijoAfirmativo() == navegador){
                navegador.getPadre().setHijoAfirmativo(pregunta);
                navegador.setPadre(pregunta);
            }
            else{
                navegador.getPadre().setHijoNegativo(pregunta);
                navegador.setPadre(pregunta);
            }
            botonGuardarEnArchivo.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Arbol modificado, puede guardar los cambios en el txt presionando el boton Guardar Archivo");
            navegador = arbol.getRaiz();
            actividad += "\n-- NUEVA SESION --\n";
            historialDePreguntas.setText(actividad);
        }
        else{
            //Siguen las preguntas
            if(navegador.getHijoNegativo().esHoja()){
                navegador = navegador.getHijoNegativo();
                labelPregunta.setText("Tu animal es "+navegador.getValor()+ "?");
                this.actividad += labelPregunta.getText()+"\n";
                historialDePreguntas.setText(actividad);
            }
            else{
                navegador = navegador.getHijoNegativo();
                labelPregunta.setText("El animal "+navegador.getValor()+ "?");
                this.actividad += labelPregunta.getText()+"\n";
                historialDePreguntas.setText(actividad);
            }
            
        }
        
    }//GEN-LAST:event_botonNoActionPerformed

    private void botonSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiActionPerformed
        // TODO add your handling code here:
        this.actividad += "Si!\n";
        historialDePreguntas.setText(actividad);
        if(navegador.esHoja()){
            JOptionPane.showMessageDialog(null,"Hemos adivinado tu animal!");            
        }
        else{
            if(navegador.getHijoAfirmativo().esHoja()){
                navegador = navegador.getHijoAfirmativo();
                labelPregunta.setText("El animal es "+navegador.getValor()+ "?");
                this.actividad += labelPregunta.getText()+"\n";
                historialDePreguntas.setText(actividad);
            }
            else{
                navegador = navegador.getHijoAfirmativo();
                labelPregunta.setText("El animal "+navegador.getValor()+ "?");
                this.actividad += labelPregunta.getText()+"\n";
                historialDePreguntas.setText(actividad);
            }
        }
        
        
    }//GEN-LAST:event_botonSiActionPerformed

    private void botonGuardarEnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarEnArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarEnArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainModal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardarEnArchivo;
    private javax.swing.JButton botonNo;
    private javax.swing.JButton botonNuevaSesion;
    private javax.swing.JButton botonSi;
    private javax.swing.JButton botonVerArbol;
    private javax.swing.JTextArea historialDePreguntas;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPregunta;
    // End of variables declaration//GEN-END:variables
}
